name: "Hello world workflow by Hritik Bhandari"

# controls when the action will run. Triggers the workflow on push to master branch
on:
  push:
    branches:
      - master #in list we start with hyphen
      - production

jobs:
  hello_world: #we create an object
   runs-on: ubuntu-latest
   steps:
    - name: "Print hello world"
      run: echo "Hello world"
